language:
  - "node_js"
node_js:
  - "8"
script:
  - "yarn test"
cache:
  yarn: true
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: 
    secure: "MGDN4/HRV7uJ8NOgUTOHfIzbHzsWIa1WZ739/V9nBHRn49Ka+XFqqhoYngclpqDH39OhMjG5/vZ6Q2N4qHGmkAVaMkuENBP9mzIQHG3rgl3M5w2aUluzd1NwP+7016N1dg8CIEuThRFzvkLA5fCiCMfN9N8ZnTqkZpT+T6W1YSCnZCvVsuoFTAOZby/sopWPoQKGNgYDt/JAH+0+C4EAtFWP/2fhQQcX8/FUDhPLjtWk5yW1i771Q3xecPhuzvHaiyZn1mCBvFQcIpXjXZ7tvWbkzRAaMha3ZedwNNrYG/mcKOnjjAE+TCC3syytKZvZcrZvqcwoDj+0KpucxUnzSRvKvs9IagZcvxXb+iKeofg1Wx4h2Grjar/updkgVZWTnkfZGF9DacNeSkWV5Uly373X13jD6oMRSOoxCjQE0nWHZ5VPHeVFcmK8qk1Zdr2gO4TvNocLAhPz/i7eUjWtk1Px5zmKL5uO85uaRG5Oc8rt52zwSt7UZtpq/qTLmCPmDzuK/xyg92UZcb5RsKMntnv5g1NQeGCP3Z3ardfSbmoe86quDa8QMwi1ZligmfsOsYcH29oSdeMfoutGc+5TWZ9PHa5kG1bDJP4Cr9FCBV+/3/isZE1hXq+I7GxG78JCd7my4B66d2jCP350OVJdBas4T34yOmoO/lIlTpwXSDo="
  secret_access_key: &1
    secure: Ys+qD0FnISIKm6fSwlxCuQSTHRSQ3fvR0sg+L6kIrQFEC5wR3AXgzjJv+fKua8dVlU/Kxs3RVe0FKQ0gMsle4HxaVA+t/lHk5Y5IyYRw4JjsSsR7rhaPWIXvrBj9svgn4vYl4gjTntQnuA08Wd0LXyO9dff0T0s67UKVRevRYA6LlYHzaYHKn5TdeWwz6bJUGBmaozWxJSkeR0yfZWnvFlz/zCsOhktlLh1H/SRWsj82+laSsyz7UKJXQELzRc3sF6vcX8H0nwWLqez0dhNavkSc7sdrWsNnqpv5Qb66XrfkqlX9vvQ82mHcJDPonfg4m6a1prvLYwxMy95Ic45sn+h5Z2zUmHY20rDN1N4hGw7JtooGLanDkotFpgVNs12/DdVgFKyyivyjllbqyX7xyQhcT9eWDFEWWAY7ttXl0ob9fm/5uFBjc1KY/LlLWclhYtMK2N2njYT7itbtYYkYU7is8HDzKQMbE8/toRlKIVRGbK/RGz5EZPvmSx9bbVoCbstIvgoOniduzda8qGcBLORhLhNVaoscKomwtcIvpbo/NO0ToyeHhOFa4M0qhWNB/VrlMa3ejUI89JD38MhHL+3TyBZ2NlFxAWRJ3eGtmavvgGNmdu4yldQ5auuMub2GIPdQL7+sU8fuMXaa+VzU2AapLtWCZrJgXbKU0EYDKOU=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: GuilhermeLLS/noted-base
    branch: main
  bucket: frontend-masters-course
- provider: codedeploy
  access_key_id:
    secure: "MGDN4/HRV7uJ8NOgUTOHfIzbHzsWIa1WZ739/V9nBHRn49Ka+XFqqhoYngclpqDH39OhMjG5/vZ6Q2N4qHGmkAVaMkuENBP9mzIQHG3rgl3M5w2aUluzd1NwP+7016N1dg8CIEuThRFzvkLA5fCiCMfN9N8ZnTqkZpT+T6W1YSCnZCvVsuoFTAOZby/sopWPoQKGNgYDt/JAH+0+C4EAtFWP/2fhQQcX8/FUDhPLjtWk5yW1i771Q3xecPhuzvHaiyZn1mCBvFQcIpXjXZ7tvWbkzRAaMha3ZedwNNrYG/mcKOnjjAE+TCC3syytKZvZcrZvqcwoDj+0KpucxUnzSRvKvs9IagZcvxXb+iKeofg1Wx4h2Grjar/updkgVZWTnkfZGF9DacNeSkWV5Uly373X13jD6oMRSOoxCjQE0nWHZ5VPHeVFcmK8qk1Zdr2gO4TvNocLAhPz/i7eUjWtk1Px5zmKL5uO85uaRG5Oc8rt52zwSt7UZtpq/qTLmCPmDzuK/xyg92UZcb5RsKMntnv5g1NQeGCP3Z3ardfSbmoe86quDa8QMwi1ZligmfsOsYcH29oSdeMfoutGc+5TWZ9PHa5kG1bDJP4Cr9FCBV+/3/isZE1hXq+I7GxG78JCd7my4B66d2jCP350OVJdBas4T34yOmoO/lIlTpwXSDo="
  secret_access_key: *1
  bucket: frontend-masters-course
  bundle_type: ''
  application: noted-base
  deployment_group: ''
  on: *2
  cleanup: 'true'
before_deploy:
- yarn run build