language:
- node_js
node_js:
- '8'
script:
- yarn test
cache:
  yarn: true
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id: AKIAT7F3WHF7OL6JBHXL
  secret_access_key: &1
    secure: a1CFN7wjRE2YWWFM87tp6Rn2KpUW1+9Rx7VouI5zy9Z3v1xvkl5zkceixaxm3NwLlsu8d8GNyIyOqLhOwsjjJGoQ/9qY8JRUGqoIy6jNRFNRjeb5zXpmJWhUqU6doXZY7Aam4iCzHWEPH9bbNriyhpAp8Y7dEqZeIkrXvvryF9Top0E3Ghu+hImzVm6Skbyuy6GWy4KFGkRMci+oHis89+w9mVLMGw/ZCjKJF4gXYcxQBzjCyBXmY8LXNa8SYs2yU9DOX/GZ927/b/t8Xe8BndwmLhrr6AGSyIncZ3zB/dEcaReYu4kCyKDKgbIf44f58w5GEGPZwahGneifr+VxEBPCOSye4YghaK1o5IBPkPvvLju4FIQdPIxYeNaRzfT/sq0sY3BkawMkxzVmKafK/Ml5O11+e7kD1cX+spAAwE8rbTwjKh/gTyWJadkTORphFO5QdE1wzS0KeVZXR4Lws5G7tGWIw2URqTikrwW10EwCGpJYO75WZAVvo+kzyCk1HFTCmXKSQhRJQND/gJchlNHKrjLb4zxwUuF0W/pGskLqnx/2D44GxUi9pfuodkHGTlBGBGx/0f6oxdOtS2PAjcHENCXFE4UjlX/kosPJaRAVnnoIxSDikU6D94vSL2QfMgSyTD6YY2wD7Y9VQCc7CqA+HUez3NZU3PAQ6mycwIc=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: GuilhermeLLS/noted-base
    branch: main
  bucket: frontend-masters-course
- provider: codedeploy
  access_key_id: AKIAT7F3WHF7OL6JBHXL
  secret_access_key: *1
  bucket: frontend-masters-course
  key: dist
  bundle_type: ''
  application: noted-base
  deployment_group: ''
  on: *2
  cleanup: 'true'
before_deploy:
- yarn run build
