script:
  - "yarn test"
cache:
  - yarn
deploy:
- provider: s3
  access_key_id: KIAT7F3WHF7OL6JBHXL
  secret_access_key: &1
    secure: Ys+qD0FnISIKm6fSwlxCuQSTHRSQ3fvR0sg+L6kIrQFEC5wR3AXgzjJv+fKua8dVlU/Kxs3RVe0FKQ0gMsle4HxaVA+t/lHk5Y5IyYRw4JjsSsR7rhaPWIXvrBj9svgn4vYl4gjTntQnuA08Wd0LXyO9dff0T0s67UKVRevRYA6LlYHzaYHKn5TdeWwz6bJUGBmaozWxJSkeR0yfZWnvFlz/zCsOhktlLh1H/SRWsj82+laSsyz7UKJXQELzRc3sF6vcX8H0nwWLqez0dhNavkSc7sdrWsNnqpv5Qb66XrfkqlX9vvQ82mHcJDPonfg4m6a1prvLYwxMy95Ic45sn+h5Z2zUmHY20rDN1N4hGw7JtooGLanDkotFpgVNs12/DdVgFKyyivyjllbqyX7xyQhcT9eWDFEWWAY7ttXl0ob9fm/5uFBjc1KY/LlLWclhYtMK2N2njYT7itbtYYkYU7is8HDzKQMbE8/toRlKIVRGbK/RGz5EZPvmSx9bbVoCbstIvgoOniduzda8qGcBLORhLhNVaoscKomwtcIvpbo/NO0ToyeHhOFa4M0qhWNB/VrlMa3ejUI89JD38MhHL+3TyBZ2NlFxAWRJ3eGtmavvgGNmdu4yldQ5auuMub2GIPdQL7+sU8fuMXaa+VzU2AapLtWCZrJgXbKU0EYDKOU=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: GuilhermeLLS/noted-base
    branch: main
  bucket: frontend-masters-course
- provider: codedeploy
  access_key_id: KIAT7F3WHF7OL6JBHXL
  secret_access_key: *1
  bucket: frontend-masters-course
  key: ''
  bundle_type: ''
  application: noted-base
  deployment_group: ''
  on: *2
  skip_cleanup: 'true'
before_deploy:
- yarn run build