language:
- node_js
node_js:
- '8'
script:
- yarn test
cache:
  yarn: true
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id:
    secure: OyJbKu76AK8FZTG5I4+O9yyuWBQJzSqPChDc/yBNtG9NwXn2r2iB7Hxjo3tyqzbQ91HxrJooimqcAoELz45lVxn2lZ+jGwnKHsJy/osd3sW463qpGpAy3NxuQa9MaKYpjcsfoJso/xwAuALNeXw50xmz8qWJk7UC+vLS+RwjOAk46LQGhuR5oTymqkGJGEBamSKJx9U+2VhsiXxfcJBCcwBFBbNhdPDNIpJwOt0SqoQk6Inn4EIcsxMOilLVVqDbi/tTvgc4sLDsENeXFMbK8FopDK4exOdpNFaFNC8SJ5ICbgqocBA4oKNyro6YmMH7NJriqjsnPFVQT6GVUisHCeYRRtydP1tDw6qxVUutsHdJs9FXtRJSA2NjbaE6PLjS1RALmIegF+Y/qdrp7oYc2o3AQ/eoon6CiyhMI0Z5tmsEOqbn25EYdNhW6/Y81Yht0neB7TpdAAGxcVRge939gOWUnt4JypUgTfSW8h+ggs6TZ0ksyjo7qYeXfdPk8pTWe+JAxLbALi3oHAds/c5trc9UV7ONWc3HE6XB06YcU6phXDgC08CMVG9idNgRMTwgRxNB1ZsGt+489ZR/cw1RQ4K+Wsv0+GO3LueQxIJ25jM/SdgAs9D64rtPB7g1BzpMJE7SGU/Zy9E5txjQ8IHsuFkMsivFCS0ywvpXkpY/j2c=
  secret_access_key: &1
    secure: a1CFN7wjRE2YWWFM87tp6Rn2KpUW1+9Rx7VouI5zy9Z3v1xvkl5zkceixaxm3NwLlsu8d8GNyIyOqLhOwsjjJGoQ/9qY8JRUGqoIy6jNRFNRjeb5zXpmJWhUqU6doXZY7Aam4iCzHWEPH9bbNriyhpAp8Y7dEqZeIkrXvvryF9Top0E3Ghu+hImzVm6Skbyuy6GWy4KFGkRMci+oHis89+w9mVLMGw/ZCjKJF4gXYcxQBzjCyBXmY8LXNa8SYs2yU9DOX/GZ927/b/t8Xe8BndwmLhrr6AGSyIncZ3zB/dEcaReYu4kCyKDKgbIf44f58w5GEGPZwahGneifr+VxEBPCOSye4YghaK1o5IBPkPvvLju4FIQdPIxYeNaRzfT/sq0sY3BkawMkxzVmKafK/Ml5O11+e7kD1cX+spAAwE8rbTwjKh/gTyWJadkTORphFO5QdE1wzS0KeVZXR4Lws5G7tGWIw2URqTikrwW10EwCGpJYO75WZAVvo+kzyCk1HFTCmXKSQhRJQND/gJchlNHKrjLb4zxwUuF0W/pGskLqnx/2D44GxUi9pfuodkHGTlBGBGx/0f6oxdOtS2PAjcHENCXFE4UjlX/kosPJaRAVnnoIxSDikU6D94vSL2QfMgSyTD6YY2wD7Y9VQCc7CqA+HUez3NZU3PAQ6mycwIc=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: GuilhermeLLS/noted-base
    branch: main
  bucket: frontend-masters-course
- provider: codedeploy
  access_key_id:
    secure: OyJbKu76AK8FZTG5I4+O9yyuWBQJzSqPChDc/yBNtG9NwXn2r2iB7Hxjo3tyqzbQ91HxrJooimqcAoELz45lVxn2lZ+jGwnKHsJy/osd3sW463qpGpAy3NxuQa9MaKYpjcsfoJso/xwAuALNeXw50xmz8qWJk7UC+vLS+RwjOAk46LQGhuR5oTymqkGJGEBamSKJx9U+2VhsiXxfcJBCcwBFBbNhdPDNIpJwOt0SqoQk6Inn4EIcsxMOilLVVqDbi/tTvgc4sLDsENeXFMbK8FopDK4exOdpNFaFNC8SJ5ICbgqocBA4oKNyro6YmMH7NJriqjsnPFVQT6GVUisHCeYRRtydP1tDw6qxVUutsHdJs9FXtRJSA2NjbaE6PLjS1RALmIegF+Y/qdrp7oYc2o3AQ/eoon6CiyhMI0Z5tmsEOqbn25EYdNhW6/Y81Yht0neB7TpdAAGxcVRge939gOWUnt4JypUgTfSW8h+ggs6TZ0ksyjo7qYeXfdPk8pTWe+JAxLbALi3oHAds/c5trc9UV7ONWc3HE6XB06YcU6phXDgC08CMVG9idNgRMTwgRxNB1ZsGt+489ZR/cw1RQ4K+Wsv0+GO3LueQxIJ25jM/SdgAs9D64rtPB7g1BzpMJE7SGU/Zy9E5txjQ8IHsuFkMsivFCS0ywvpXkpY/j2c=
  secret_access_key: *1
  bucket: frontend-masters-course
  bundle_type: ''
  application: noted-base
  deployment_group: ''
  on: *2
  cleanup: 'true'
before_deploy:
- yarn run build
env:
  global:
    - secure: OyJbKu76AK8FZTG5I4+O9yyuWBQJzSqPChDc/yBNtG9NwXn2r2iB7Hxjo3tyqzbQ91HxrJooimqcAoELz45lVxn2lZ+jGwnKHsJy/osd3sW463qpGpAy3NxuQa9MaKYpjcsfoJso/xwAuALNeXw50xmz8qWJk7UC+vLS+RwjOAk46LQGhuR5oTymqkGJGEBamSKJx9U+2VhsiXxfcJBCcwBFBbNhdPDNIpJwOt0SqoQk6Inn4EIcsxMOilLVVqDbi/tTvgc4sLDsENeXFMbK8FopDK4exOdpNFaFNC8SJ5ICbgqocBA4oKNyro6YmMH7NJriqjsnPFVQT6GVUisHCeYRRtydP1tDw6qxVUutsHdJs9FXtRJSA2NjbaE6PLjS1RALmIegF+Y/qdrp7oYc2o3AQ/eoon6CiyhMI0Z5tmsEOqbn25EYdNhW6/Y81Yht0neB7TpdAAGxcVRge939gOWUnt4JypUgTfSW8h+ggs6TZ0ksyjo7qYeXfdPk8pTWe+JAxLbALi3oHAds/c5trc9UV7ONWc3HE6XB06YcU6phXDgC08CMVG9idNgRMTwgRxNB1ZsGt+489ZR/cw1RQ4K+Wsv0+GO3LueQxIJ25jM/SdgAs9D64rtPB7g1BzpMJE7SGU/Zy9E5txjQ8IHsuFkMsivFCS0ywvpXkpY/j2c=
    - secure: a1CFN7wjRE2YWWFM87tp6Rn2KpUW1+9Rx7VouI5zy9Z3v1xvkl5zkceixaxm3NwLlsu8d8GNyIyOqLhOwsjjJGoQ/9qY8JRUGqoIy6jNRFNRjeb5zXpmJWhUqU6doXZY7Aam4iCzHWEPH9bbNriyhpAp8Y7dEqZeIkrXvvryF9Top0E3Ghu+hImzVm6Skbyuy6GWy4KFGkRMci+oHis89+w9mVLMGw/ZCjKJF4gXYcxQBzjCyBXmY8LXNa8SYs2yU9DOX/GZ927/b/t8Xe8BndwmLhrr6AGSyIncZ3zB/dEcaReYu4kCyKDKgbIf44f58w5GEGPZwahGneifr+VxEBPCOSye4YghaK1o5IBPkPvvLju4FIQdPIxYeNaRzfT/sq0sY3BkawMkxzVmKafK/Ml5O11+e7kD1cX+spAAwE8rbTwjKh/gTyWJadkTORphFO5QdE1wzS0KeVZXR4Lws5G7tGWIw2URqTikrwW10EwCGpJYO75WZAVvo+kzyCk1HFTCmXKSQhRJQND/gJchlNHKrjLb4zxwUuF0W/pGskLqnx/2D44GxUi9pfuodkHGTlBGBGx/0f6oxdOtS2PAjcHENCXFE4UjlX/kosPJaRAVnnoIxSDikU6D94vSL2QfMgSyTD6YY2wD7Y9VQCc7CqA+HUez3NZU3PAQ6mycwIc=
